export const USER_ACTION_TYPES = {
    SET_CURRET_USER:'user/SET_CURRENT_uSER',
    CHECK_USER_SESSION:' user/CHECK_USER_SESSION',
    GOOGLE_SIGN_IN_START:'user/GOOGLE_SIGN_IN_START',
    EMAIL_SIGN_IN_START:'user/EMAIL_SIGN_IN_START',
    SIGN_IN_SUCCESS:'user/SIGN_IN_SUCCESS',
    SIGN_iN_FAILURE:'user/SIGN_IN_FAILURE'
};


